// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package avayacpaas.actions;

import java.util.UUID;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Generate UUID uniquely identifying a conference
 */
public class CreateConferenceIdentifier extends CustomJavaAction<java.lang.String>
{
	private java.lang.String defaultIdentifier;

	public CreateConferenceIdentifier(IContext context, java.lang.String defaultIdentifier)
	{
		super(context);
		this.defaultIdentifier = defaultIdentifier;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if(this.defaultIdentifier != null && this.defaultIdentifier.length() > 0) {
			return this.defaultIdentifier;
		}
		
		return UUID.randomUUID().toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CreateConferenceIdentifier";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
