// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package avayacpaas.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * This method will create and return a URL hosting InboundXML for <Conferencel> tag.
 * 
 * It will add the following HTTP Parameters:
 * -- ConferenceIdentifier: Unique identifier for the conference 
 * -- DefaultURL: Default conference URL if exists
 * -- CallbackURL: URL requested when the dialed call connects and ends
 * -- StartConferenceOnEnter: Boolean value specifying if conference should begin upon entrance. Default Value: false. Allowed Value: true or false.
 * -- Method: Method used to request the action URL.
 * -- Beep:Boolean value specifying if a beep should play upon entrance to conference. Default Value: false. Allowed Value: true or false.
 */
public class GetInboundXMLConference extends CustomJavaAction<java.lang.String>
{
	private java.lang.String conferenceIdentifier;
	private java.lang.String defaultUrl;
	private java.lang.String callbackUrl;
	private java.lang.Boolean startConferenceOnEnter;
	private java.lang.Boolean endConferenceOnExit;
	private java.lang.Boolean beep;
	private avayacpaas.proxies.HttpMethod method;

	public GetInboundXMLConference(IContext context, java.lang.String conferenceIdentifier, java.lang.String defaultUrl, java.lang.String callbackUrl, java.lang.Boolean startConferenceOnEnter, java.lang.Boolean endConferenceOnExit, java.lang.Boolean beep, java.lang.String method)
	{
		super(context);
		this.conferenceIdentifier = conferenceIdentifier;
		this.defaultUrl = defaultUrl;
		this.callbackUrl = callbackUrl;
		this.startConferenceOnEnter = startConferenceOnEnter;
		this.endConferenceOnExit = endConferenceOnExit;
		this.beep = beep;
		this.method = method == null ? null : avayacpaas.proxies.HttpMethod.valueOf(method);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE

		// Return default URL if already exists
		if (this.defaultUrl != null && this.defaultUrl.length() > 0) {
			return this.defaultUrl;
		}

		// Generate new URL if empty
		StringBuilder urlConference = new StringBuilder(avayacpaas.proxies.constants.Constants.getINBOUND_XML_BASE_URL_CONFERENCE());
		urlConference.append("?Conference=" + this.conferenceIdentifier);
		
		if(this.callbackUrl != null && this.callbackUrl.length() > 0) {
			urlConference.append("&CallbackURL=" + this.callbackUrl);
		}
		if(this.startConferenceOnEnter != null ) {
			urlConference.append("&Start=" + this.startConferenceOnEnter);
		}
		if(this.endConferenceOnExit != null) {
			urlConference.append("&End=" + this.endConferenceOnExit);
		}
		if(this.beep != null) {
			urlConference.append("&Beep=" + this.beep);
		}
		if(this.method != null) {
			urlConference.append("&Method=" + this.method.name());
		}
		return urlConference.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetInboundXMLConference";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
