// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package avayacpaas.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import avayacpaas.proxies.ContactNumber;
import avayacpaas.proxies.constants.Constants;

public class GetListOfNumbersFromString extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String contactNumberListString;

	public GetListOfNumbersFromString(IContext context, java.lang.String contactNumberListString)
	{
		super(context);
		this.contactNumberListString = contactNumberListString;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		if(this.contactNumberListString == null) {
			return null;
		}
		
		String[] splitContactNoList = this.contactNumberListString.split(Constants.getCONTACT_NO_DELIMITER());

		List<IMendixObject> returnList = new ArrayList<IMendixObject>();

		for (int i = 0; i < splitContactNoList.length; i++) {
			ContactNumber curNumber = new ContactNumber(this.getContext());
			curNumber.setNumber(splitContactNoList[i]);
			returnList.add(curNumber.getMendixObject());
		}
		return returnList;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetListOfNumbersFromString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
